interface Course {
    code: string;
    name: string;
}

interface Department {
    name: string;
    courses: Course[];
}

interface School {
    name: string;
    departments: Department[];
}

export const coursesData: { schools: School[] } = {
    "schools": [
        {
            "name": "SBE (School of Business and Economic)",
            "departments": [
                {
                    "name": "Department of Accounting & Finance",
                    "courses": [
                        { "code": "ACT 201", "name": "Introduction to Financial Accounting" },
                        { "code": "ACT 202", "name": "Introduction to Managerial Accounting" },
                        { "code": "ACT 310", "name": "Intermediate Accounting - I" },
                        { "code": "ACT 320", "name": "Intermediate Accounting - II" },
                        { "code": "ACT 360", "name": "Advanced Managerial Accounting" },
                        { "code": "ACT 370", "name": "Taxation" },
                        { "code": "ACT 380", "name": "Audit and Assurance" },
                        { "code": "ACT 410 / FIN 410", "name": "Financial Statement Analysis" },
                        { "code": "ACT 430", "name": "Accounting Information Systems" },
                        { "code": "ACT 460", "name": "Advanced Financial Accounting" },
                        { "code": "FIN 254", "name": "Introduction to Financial Management" },
                        { "code": "FIN 433", "name": "Financial Markets & Institutions" },
                        { "code": "FIN 435", "name": "Investment Theory" },
                        { "code": "FIN 440", "name": "Corporate Finance" },
                        { "code": "FIN 444", "name": "International Financial Management" },
                        { "code": "FIN 455", "name": "Financial Modeling Using Excel" },
                        { "code": "FIN 464", "name": "Bank Management" },
                        { "code": "FIN 470", "name": "Insurance and Risk Management" },
                        { "code": "FIN 480", "name": "Financial Derivatives" }
                    ]
                },
                {
                    "name": "Department of Marketing & International Business",
                    "courses": [
                        { "code": "MKT202", "name": "Introduction to Marketing" },
                        { "code": "MKT337", "name": "Promotional Management" },
                        { "code": "MKT344", "name": "Consumer Behavior" },
                        { "code": "MKT460", "name": "Strategic Marketing" },
                        { "code": "MKT470", "name": "Marketing Research" },
                        { "code": "MKT330", "name": "Digital Marketing" },
                        { "code": "MKT355", "name": "Agricultural Marketing" },
                        { "code": "MKT382", "name": "International Marketing" },
                        { "code": "MKT412", "name": "Services Marketing" },
                        { "code": "MKT417", "name": "Export Import Management" },
                        { "code": "MKT445", "name": "Sales Management" },
                        { "code": "MKT450", "name": "Marketing Channels" },
                        { "code": "MKT465", "name": "Brand Management" },
                        { "code": "MKT475", "name": "Marketing Analytics" }
                    ]
                },
                {
                    "name": "Department of Management",
                    "courses": [
                        { "code": "BUS 135", "name": "Applied Business Mathematics" },
                        { "code": "BUS172", "name": "Introduction to statistics" },
                        { "code": "BUS 173", "name": "Applied statistics" },
                        { "code": "BUS 251", "name": "Business Communication" },
                        { "code": "BUS 498", "name": "Internship" },
                        { "code": "HRM 340", "name": "Training and Development" },
                        { "code": "HRM 360", "name": "Planning and Staffing" },
                        { "code": "HRM 370", "name": "Leadership Theory and Practice" },
                        { "code": "HRM 380", "name": "Compensation" },
                        { "code": "HRM 450", "name": "Labor Management Relations" },
                        { "code": "HRM 470", "name": "Negotiations" },
                        { "code": "MGT 212", "name": "Organizational Management" },
                        { "code": "MGT 314", "name": "Operations & Supply Chain Management" },
                        { "code": "MGT 321", "name": "Organizational Behavior" },
                        { "code": "MGT 351", "name": "Human Resource Management" },
                        { "code": "MGT 368", "name": "Entrepreneurship" },
                        { "code": "MGT 330", "name": "Designing Effective Organizations" },
                        { "code": "MGT 410", "name": "Organizational Development and Change Management" },
                        { "code": "MGT 489", "name": "Strategic Management" },
                        { "code": "MGT 490", "name": "Project Management" },
                        { "code": "MIS 107", "name": "Information System & Computing" },
                        { "code": "MIS 207", "name": "E-Business" },
                        { "code": "MIS210", "name": "Concepts of Computer Programming" },
                        { "code": "MIS310", "name": "Database Systems for Business" },
                        { "code": "MIS320", "name": "Digital Enterprise Management" },
                        { "code": "MIS410", "name": "Business Intelligence" },
                        { "code": "MIS450", "name": "Data Communication and Networking for Business" },
                        { "code": "MIS470", "name": "Systems Analysis and Design" },
                        { "code": "SCM310", "name": "Logistics and Transportation" },
                        { "code": "SCM 320", "name": "Demand Planning and Fulfilment" },
                        { "code": "MGT/SCM 360", "name": "Services Management" },
                        { "code": "SCM 450", "name": "Global Procurement and Sourcing" }
                    ]
                },
                {
                    "name": "Department of Economics",
                    "courses": [
                        { "code": "Eco101", "name": "introduction to Microeconomics" },
                        { "code": "Eco 104", "name": "principles of macroeconomics" },
                        { "code": "Eco172", "name": "introduction to statistic" },
                        { "code": "Eco173", "name": "applied statistic" },
                        { "code": "Eco201", "name": "Intermediate Microeconomics Theory" },
                        { "code": "ECO204", "name": "intermediate Macroeconomics theory" },
                        { "code": "Eco372", "name": "introduction to economics" },
                        { "code": "Eco490", "name": "senior seminer" },
                        { "code": "Eco317", "name": "money and banking" },
                        { "code": "Eco328", "name": "international economics" },
                        { "code": "Eco349", "name": "economy of Bangladesh" },
                        { "code": "Eco354", "name": "environmental & natural resources economics" },
                        { "code": "Eco496", "name": "History of Economics thought" },
                        { "code": "Eco414", "name": "Public Finance" },
                        { "code": "Eco441", "name": "labor Economics" },
                        { "code": "Eco443", "name": "health economics" },
                        { "code": "Eco415", "name": "economic development" },
                        { "code": "Eco492", "name": "special topic in economics" }
                    ]
                }
            ]
        },
        {
            "name": "SEPS (School of Engineering and Physical Science)",
            "departments": [
                {
                    "name": "Department of Architecture",
                    "courses": [
                        { "code": "ARC 111", "name": "Foundation Design Studio I- Artistic Development" },
                        { "code": "ARC 112", "name": "Foundation Design Studio II- Form and Composition" },
                        { "code": "ARC 121", "name": "Graphics I- Basic Drawing" },
                        { "code": "ARC 122", "name": "Graphics II- Rendering" },
                        { "code": "ARC 123", "name": "Graphics III- Digital Presentation" },
                        { "code": "ARC 131", "name": "Sources in Architecture I- Artistic Appreciation" },
                        { "code": "ARC 132", "name": "Sources in Architecture II- Introduction to Visual Studies, Word and Images" },
                        { "code": "ARC 133:1", "name": "Parameters in Design I- Aesthetic and Design" },
                        { "code": "ARC 200", "name": "Craft and Design- Observation and Documentation" },
                        { "code": "ARC 213", "name": "Allied Design Studio- Dimension and Product" },
                        { "code": "ARC 214", "name": "Architecture Design Studio I- Function and Analysis" },
                        { "code": "ARC 215", "name": "Architecture Design Studio II- Simple Function" },
                        { "code": "ARC 241", "name": "Architectural Heritage I- World I" },
                        { "code": "ARC 242", "name": "Architectural Heritage II- World II" },
                        { "code": "ARC 251", "name": "Introduction to Urban Design and Environmental Planning" },
                        { "code": "ARC 261", "name": "Environment and Building System I- Climate and Design" },
                        { "code": "ARC 262", "name": "Environment and Building System II- Building Physics" },
                        { "code": "ARC 263", "name": "Environment and Building System III- Building Services" },
                        { "code": "ARC 264", "name": "Environment and Building System IV- Design Integration" },
                        { "code": "ARC 271", "name": "Construction I- Materials" },
                        { "code": "ARC 272", "name": "Construction II- Technology" },
                        { "code": "ARC 273", "name": "Construction III- Workshop" },
                        { "code": "ARC 281", "name": "Building Structures I: Basic Principles" },
                        { "code": "ARC 282", "name": "Building Structures II" },
                        { "code": "ARC 283", "name": "Building Structures III" },
                        { "code": "ARC 293", "name": "Design-Related-Media" },
                        { "code": "ARC 310", "name": "Interior Design Studio" },
                        { "code": "ARC 316", "name": "Professional Studies Studio I- Form and Function" },
                        { "code": "ARC 317", "name": "Professional Studies Studio II- Complex Function" },
                        { "code": "ARC 318", "name": "Professional Studies Studio III- Complex Function" },
                        { "code": "ARC 324", "name": "Graphics IV-Working Details" },
                        { "code": "ARC 334", "name": "Parameters in Design II- Theory and Methods" },
                        { "code": "ARC 336", "name": "Architecture and Urbanism- Space, Culture and Urban Design" },
                        { "code": "ARC 343", "name": "Architectural Heritage III- India" },
                        { "code": "ARC 344", "name": "Architectural Heritage IV- Bengal" },
                        { "code": "ARC 346", "name": "Architectural Heritage V- Contemporary South and Southeast Asia" },
                        { "code": "ARC 347", "name": "Architectural Heritage VI- Islamic" },
                        { "code": "ARC 348", "name": "Built Heritage and Conservation" },
                        { "code": "ARC 365", "name": "Design for the Tropics" },
                        { "code": "ARC 384", "name": "Building Structures IV" },
                        { "code": "ARC 394", "name": "Special Topic I (Technology, Environment or Science)" },
                        { "code": "ARC 410", "name": "Landscape Design Laboratory" },
                        { "code": "ARC 418", "name": "Design and Allied Studies Studio I" },
                        { "code": "ARC 419", "name": "Design and Allied Studies Studio II" },
                        { "code": "ARC 436", "name": "Buildings, Land, and Cultural Traditions- Diversity and Change" },
                        { "code": "ARC 437", "name": "Professional Practice, Ethics and Society" },
                        { "code": "ARC 438", "name": "Environmental Psychology" },
                        { "code": "ARC 439", "name": "Management and Business Administration in Architecture" },
                        { "code": "ARC 445", "name": "Contemporary Design- Precedents and Analyses" },
                        { "code": "ARC 452", "name": "Land-Use, Infrastructure and Transport Planning" },
                        { "code": "ARC 453", "name": "Human Settlement- Policy and Planning" },
                        { "code": "ARC 454", "name": "Human Geography- Settlement and Development" },
                        { "code": "ARC 455", "name": "Advanced Urban Design and Planning Applications" },
                        { "code": "ARC 456", "name": "Rural Studies" },
                        { "code": "ARC 457", "name": "Urbanism and Local Context" },
                        { "code": "ARC 458", "name": "Residential Building Design" },
                        { "code": "ARC 459", "name": "Non-Residential Building Design" },
                        { "code": "ARC 466", "name": "Ecology and Bio-Climatic Design" },
                        { "code": "ARC 474", "name": "Construction IV- Documents and Management" },
                        { "code": "ARC 475", "name": "Field Survey, Measured Drawing and Documentation" },
                        { "code": "ARC 485", "name": "Advanced Architectural Structure I" },
                        { "code": "ARC 486", "name": "Advanced Architectural Structure II" },
                        { "code": "ARC 492", "name": "Independent Study" },
                        { "code": "ARC 495", "name": "Special Topic II (Design, Theory or Settlement)" },
                        { "code": "ARC 500", "name": "Professional Internship (supervised training)" },
                        { "code": "ARC 510", "name": "Advanced Studies Studio I" },
                        { "code": "ARC 519", "name": "Advanced Studies Studio II- Thesis Project" },
                        { "code": "ARC 535", "name": "Parameters in Design III- Pedagogy and Discourse" },
                        { "code": "ARC 576", "name": "Building Automation and Hi-Tech Architecture" },
                        { "code": "ARC 577", "name": "Building Systems Integration" },
                        { "code": "ARC 578", "name": "Building Economics" },
                        { "code": "ARC 579", "name": "Building Safety and Security" },
                        { "code": "ARC 596", "name": "Thesis Documentation- Research and Development" },
                        { "code": "ARC 597", "name": "Methods of Inquiry on Architecture, City and Environment" },
                        { "code": "ARC 598", "name": "Seminar on Art, Architecture, Society and Culture" }
                    ]
                },
                {
                    "name": "Department of Civil & Environmental Engineering",
                    "courses": [
                        { "code": "CEE 100", "name": "Introduction to Civil & Environmental Engineering" },
                        { "code": "CEE 110", "name": "Computer-Aided Drawing (CAD) for Engineers" },
                        { "code": "CEE 330", "name": "Structural Analysis & Design I" },
                        { "code": "CEE 330L", "name": "Structural Analysis & Design Lab" },
                        { "code": "CEE 331", "name": "Structural Analysis & Design II" },
                        { "code": "CEE 331L", "name": "Structural Analysis & Design Lab (II)" },
                        { "code": "CEE 335", "name": "Reinforced Concrete Design I" },
                        { "code": "CEE 335L", "name": "Reinforced Concrete Design Lab" },
                        { "code": "CEE 430", "name": "Reinforced Concrete Design II" },
                        { "code": "CEE 240", "name": "Intro to Soil Mechanics & Foundation Engineering" },
                        { "code": "CEE 240L", "name": "Soil Mechanics Lab" },
                        { "code": "CEE 340", "name": "Advanced Foundation Engineering" },
                        { "code": "CEE 250", "name": "Intro to Transportation Engineering" },
                        { "code": "CEE 250L", "name": "Transportation Engineering Lab" },
                        { "code": "CEE 350", "name": "Traffic Analysis & Design" },
                        { "code": "CEE 360", "name": "Open‑Channel Hydraulics" },
                        { "code": "CEE 360L", "name": "Open‑Channel Hydraulics Lab" },
                        { "code": "CEE 460", "name": "Groundwater Hydraulics" },
                        { "code": "CEE 370", "name": "Water Supply & Treatment" },
                        { "code": "CEE 370L", "name": "Lab: Water Supply & Treatment" },
                        { "code": "CEE 373", "name": "Sanitation & Wastewater Engineering" },
                        { "code": "CEE 373L", "name": "Sanitation & Wastewater Engineering Lab" },
                        { "code": "ENV 373", "name": "Environmental Impact Assessment" },
                        { "code": "CEE 470", "name": "Solid & Hazardous Waste Engineering" },
                        { "code": "CEE 499A", "name": "Engineering Project I" },
                        { "code": "CEE 499B", "name": "Engineering Project II" },
                        { "code": "CEE 499C", "name": "Engineering Project III" },
                        { "code": "CEE 498", "name": "Co‑op / Internship (mandatory, zero credit)" },
                        { "code": "CEE 431", "name": "Intro to Structural Dynamics" },
                        { "code": "CEE 432", "name": "Composite Structures" },
                        { "code": "CEE 433", "name": "Finite Element Methods" },
                        { "code": "CEE 434", "name": "Advanced Reinforced Concrete Design" },
                        { "code": "CEE 435", "name": "Prestressed Concrete" },
                        { "code": "CEE 437", "name": "Behavior & Design of Metal Structures" },
                        { "code": "CEE 439", "name": "Earthquake‑Resistant Design" },
                        { "code": "CEE 441", "name": "Advanced Geotechnical Engineering" },
                        { "code": "CEE 442", "name": "Earthen Dam & Slope Stability" },
                        { "code": "CEE 443", "name": "Earth Retaining Structures" },
                        { "code": "CEE 444", "name": "Advanced Soil Mechanics" },
                        { "code": "CEE 450", "name": "Road & Traffic Safety Engineering" },
                        { "code": "CEE 452", "name": "Pavement Analysis, Design & Construction" },
                        { "code": "CEE 454", "name": "Advanced Traffic Engineering" },
                        { "code": "CEE 458", "name": "Transportation Systems Engineering & Planning" },
                        { "code": "CEE 459", "name": "Geometric Analysis & Design of Roads" },
                        { "code": "CEE 463", "name": "Integrated Water Resources Planning & Management" },
                        { "code": "CEE 465", "name": "River Engineering" },
                        { "code": "CEE 467", "name": "Irrigation & Drainage Engineering" },
                        { "code": "CEE 473", "name": "Coastal & Estuarine Analysis" },
                        { "code": "CEE 475", "name": "Water Resources & Environmental Modeling" }
                    ]
                },
                {
                    "name": "Department of Electrical & Computer Engineering",
                    "courses": [
                        { "code": "EEE 141 + CL", "name": "Electrical Circuits I" },
                        { "code": "EEE 241 + CL", "name": "Electrical Circuits II" },
                        { "code": "EEE 111 + CL", "name": "Analog Electronics I" },
                        { "code": "EEE 211 + IL", "name": "Digital Logic Design" },
                        { "code": "EEE 311 + CL", "name": "Analog Electronics II" },
                        { "code": "EEE 221", "name": "Signals & Systems" },
                        { "code": "EEE 361", "name": "Electromagnetic Fields & Waves" },
                        { "code": "EEE 342 + CL", "name": "Control Engineering" },
                        { "code": "EEE 363 + CL", "name": "Electrical Machines" },
                        { "code": "EEE 312", "name": "Power Electronics" },
                        { "code": "EEE 362", "name": "Power Systems" },
                        { "code": "EEE 321 + IL", "name": "Introduction to Communication Systems" },
                        { "code": "EEE 452", "name": "Engineering Economics" },
                        { "code": "EEE 299", "name": "Junior Design Project (1 credit)" },
                        { "code": "EEE 499A / 499B", "name": "Senior Design I & II (1.5 credits each)" },
                        { "code": "EEE 498 (or 498R)", "name": "Co-Op / Internship / Directed Research (non-credit)" },
                        { "code": "ENG 102", "name": "English courses" },
                        { "code": "ENG 103", "name": "English courses" },
                        { "code": "ENG 111", "name": "English courses" },
                        { "code": "ENG 115", "name": "English courses" },
                        { "code": "PHI 104", "name": "Ethics" },
                        { "code": "HIS 101 / 102", "name": "Humanities & Social Sciences" },
                        { "code": "SOC 101 / ANT 101 / ENV 203 / GEO 205", "name": "Humanities & Social Sciences" },
                        { "code": "POL 101 / 104", "name": "Humanities & Social Sciences" },
                        { "code": "ECO 101 / 104", "name": "Humanities & Social Sciences" },
                        { "code": "MAT 116", "name": "Calculus & Linear Algebra" },
                        { "code": "MAT 120", "name": "Calculus & Linear Algebra" },
                        { "code": "MAT 125", "name": "Calculus & Linear Algebra" },
                        { "code": "MAT 130", "name": "Calculus & Linear Algebra" },
                        { "code": "MAT 250", "name": "Calculus & Linear Algebra" },
                        { "code": "MAT 350", "name": "Calculus & Linear Algebra" },
                        { "code": "MAT 361", "name": "Calculus & Linear Algebra" },
                        { "code": "PHY 107+CL", "name": "Science with Lab" },
                        { "code": "PHY 108+CL", "name": "Science with Lab" },
                        { "code": "CHE 101+CL", "name": "Science with Lab" },
                        { "code": "BIO 103+CL", "name": "Science with Lab" },
                        { "code": "CSE 115 + CL", "name": "Programming Language I" },
                        { "code": "ETE 131 + ETE131L", "name": "Introduction to Telecommunication & Computer Engineering (lab)" },
                        { "code": "ETE 132", "name": "Computer Programming (with lab)" },
                        { "code": "ETE 211", "name": "Analog Electronics (with lab)" },
                        { "code": "ETE 212", "name": "Digital Logic Design (with lab)" },
                        { "code": "ETE 221", "name": "Signals & Systems" },
                        { "code": "ETE 241", "name": "Electrical Circuits I (with lab)" },
                        { "code": "ETE 283", "name": "Design Lab I" },
                        { "code": "ETE 311", "name": "Digital Electronics & Pulse Techniques (lab)" },
                        { "code": "ETE 321", "name": "Introduction to Communication Systems (lab)" },
                        { "code": "ETE 331", "name": "Data Communications & Computer Networks (lab)" },
                        { "code": "ETE 332", "name": "Microprocessors & Assembly Language (lab)" },
                        { "code": "ETE 341", "name": "Electrical Circuits II (lab)" },
                        { "code": "ETE 361", "name": "Electromagnetic Field Theory" },
                        { "code": "ETE 383", "name": "Design Lab II" },
                        { "code": "ETE 411", "name": "Semiconductor Devices & Technology" },
                        { "code": "ETE 412", "name": "Introduction to VLSI (lab)" },
                        { "code": "ETE 422", "name": "Principles of Digital Communications" },
                        { "code": "ETE 423", "name": "Telecom Networks" },
                        { "code": "ETE 424", "name": "Mobile & Wireless Communications (lab)" },
                        { "code": "ETE 426", "name": "Fiber Optic Communications (lab)" },
                        { "code": "ETE 471", "name": "Digital Signal Processing (lab)" },
                        { "code": "ETE 481 / 482", "name": "Advanced Comm Lab I & II" },
                        { "code": "ETE 498 / 499", "name": "Senior Project/Internship (3 credits)" },
                        { "code": "ETE 312", "name": "Power Electronics" },
                        { "code": "ETE 333", "name": "Artificial Intelligence" },
                        { "code": "ETE 334", "name": "Internet & Web Technology" },
                        { "code": "ETE 406", "name": "IP Telephony" },
                        { "code": "ETE 473", "name": "Image Processing" },
                        { "code": "ETE 400", "name": "Special Topics" },
                        { "code": "CSE 115", "name": "Computing Concepts + Lab" },
                        { "code": "CSE 115L", "name": "Computing Concepts + Lab" },
                        { "code": "CSE 135 + 135L", "name": "Programming fundamentals" },
                        { "code": "CSE 173", "name": "Discrete Math" },
                        { "code": "CSE 225 + IL", "name": "Data Structures & Lab" },
                        { "code": "CSE 231 + IL", "name": "Digital Logic" },
                        { "code": "CSE 232", "name": "Computer Organization & Design" },
                        { "code": "CSE 243 + 243L", "name": "Electrical Circuits + Lab" },
                        { "code": "CSE 253 + 253L", "name": "Electronics I + Lab" },
                        { "code": "CSE 332", "name": "CSE 332" },
                        { "code": "CSE  311", "name": "CSE 311" },
                        { "code": "CSE 323", "name": "CSE 323" },
                        { "code": "CSE 373", "name": "CSE 373" }
                    ]
                },
                {
                    "name": "Department of Mathematics & Physics",
                    "courses": [
                        { "code": "Bus112", "name": "Introduction to Business Mathematics" },
                        { "code": "MAT 116", "name": "Pre-calculus" },
                        { "code": "MAT 120", "name": "Calculus and Analytic Geometry- I" },
                        { "code": "MAT 125", "name": "Introduction to Linear Algebra" },
                        { "code": "MAT 130", "name": "Calculus and Analytic Geometry II" },
                        { "code": "MAT240", "name": "Calculus and Analytic Geometry III" },
                        { "code": "MAT250", "name": "Calculus and Analytic Geometry IV" },
                        { "code": "MAT350", "name": "Engineering Mathematics" },
                        { "code": "MAT361", "name": "Probability and Statistics" },
                        { "code": "MAT370", "name": "Real Analysis" },
                        { "code": "MAT480", "name": "Differential Equations" },
                        { "code": "MAT481", "name": "Numerical Methods" },
                        { "code": "MAT482", "name": "Complex Variables and Its Applications" },
                        { "code": "MAT483", "name": "Mathematical Control Theory and Applications" },
                        { "code": "MAT485", "name": "Operations Research" },
                        { "code": "MAT490", "name": "Advanced Engineering Mathematics" },
                        { "code": "MAT495", "name": "Abstract Algebra" },
                        { "code": "PHY105", "name": "Fundamentals of Physics" },
                        { "code": "PHY105L", "name": "Lab of Fundamentals of Physics" },
                        { "code": "PHY107", "name": "General Physics I" },
                        { "code": "PHY107L", "name": "Physics I Lab" },
                        { "code": "PHY108", "name": "General Physics II" },
                        { "code": "PHY108L", "name": "General Physics II Lab" },
                        { "code": "PHY230", "name": "Properties of Matter" },
                        { "code": "PHY240", "name": "Waves and Oscillations" },
                        { "code": "PHY250", "name": "Modern Physics I" },
                        { "code": "PHY260", "name": "Thermal Physics" },
                        { "code": "PHY335", "name": "Electronic Circuits" },
                        { "code": "PHY350", "name": "Modern Physics II" },
                        { "code": "PHY360", "name": "Computational Physics" },
                        { "code": "PHY370", "name": "Biomedical Physics" },
                        { "code": "PHY380", "name": "Nanotechnology" },
                        { "code": "BSC201", "name": "Basic Science Support- Math and Physics" },
                        { "code": "MAT140", "name": "Introduction to Probability and Statistics for Engineers" },
                        { "code": "MAT230", "name": "Linear and Vector Algebra for Engineers" },
                        { "code": "MAT260", "name": "Differential Equations and Orthogonal Functions" }
                    ]
                }
            ]
        },
        {
            "name": "School of Humanities & Social Science",
            "departments": [
                {
                    "name": "English",
                    "courses": [
                        { "code": "ENG 102", "name": "Introduction to Composition" },
                        { "code": "ENG 103", "name": "Intermediate Composition" },
                        { "code": "ENG 111", "name": "Public Speaking" },
                        { "code": "ENG 105", "name": "Advanced Composition (argumentative writing & research skills)" },
                        { "code": "ENG 210", "name": "Introduction to Linguistics" },
                        { "code": "ENG 211", "name": "Second Language Acquisition Theory" },
                        { "code": "ENG 212", "name": "History of the English Language" },
                        { "code": "ENG 321", "name": "Psycholinguistics (requires ENG 210)" },
                        { "code": "ENG 401", "name": "Contrastive Grammar (English-Bengali comparison)" },
                        { "code": "ENG 406", "name": "Discourse Analysis (requires ENG 336)" },
                        { "code": "ENG 416", "name": "Stylistics (requires ENG 371)" },
                        { "code": "ENG 426", "name": "Generative Grammar in Modern English (requires ENG 371)" },
                        { "code": "ENG 208", "name": "Introduction to Journalism" },
                        { "code": "ENG 219", "name": "European Classics in Translation" },
                        { "code": "ENG 222", "name": "Survey of American Literature" },
                        { "code": "ENG 223", "name": "Survey of British Literature" },
                        { "code": "ENG 225", "name": "Survey of South-Asian Literature in English" },
                        { "code": "ENG 230", "name": "Introduction to Poetry" },
                        { "code": "ENG 301", "name": "Poetry of the English Renaissance" },
                        { "code": "ENG 304", "name": "Elizabethan & Jacobean Drama (excluding Shakespeare)" },
                        { "code": "ENG 318", "name": "Materials Development Principles" },
                        { "code": "ENG 334", "name": "Syllabus Design" },
                        { "code": "ENG 370", "name": "Business Communication" },
                        { "code": "ENG 450", "name": "Teaching Techniques" },
                        { "code": "ENG 451", "name": "Teaching Reading" },
                        { "code": "ENG 452", "name": "Teaching Grammar" },
                        { "code": "ENG 453", "name": "Teaching Composition" },
                        { "code": "ENG 454", "name": "Teaching Listening & Speaking" },
                        { "code": "ENG 455", "name": "Computer-Assisted Language Learning" },
                        { "code": "ENG 456", "name": "Testing & Evaluation" },
                        { "code": "ENG 491", "name": "Teaching Practicum" },
                        { "code": "ENG 377", "name": "Testing & Evaluation or similar (sometimes identified off‑list)" }
                    ]
                },
                {
                    "name": "Department of Political Science & Sociology",
                    "courses": [
                        { "code": "POL 101", "name": "Introduction to Political Science" },
                        { "code": "POL 104", "name": "Introduction to Good Governance" },
                        { "code": "POL 202", "name": "Introduction to International Relations" },
                        { "code": "INT 201", "name": "Global Security Perspectives (offered by the same department)" },
                        { "code": "PAD 201", "name": "Introduction to Public Administration" },
                        { "code": "SOC 101", "name": "Introduction to Sociology" },
                        { "code": "SOC 103", "name": "Introduction to Criminology" },
                        { "code": "SOC 201", "name": "Contemporary Issues in Gender Relationship" },
                        { "code": "TNM 201", "name": "Television and New Media" },
                        { "code": "WMS 201", "name": "Gender and Development" }
                    ]
                },
                {
                    "name": "Department of Law",
                    "courses": [
                        { "code": "LAW 101", "name": "Introduction to Legal System & Legal Processes (3 cr)" },
                        { "code": "LAW 201", "name": "Constitutional Law of Bangladesh (4 cr)" },
                        { "code": "LAW 107", "name": "Law of Contract & Restitution (4 cr)" },
                        { "code": "LAW 211", "name": "Family & Property Law (4 cr)" },
                        { "code": "LAW 213", "name": "Law of Crimes (4 cr)" },
                        { "code": "LAW 405", "name": "Labour & Employment Law (3 cr)" },
                        { "code": "LAW 417", "name": "Banking & Foreign Exchange Law (3 cr)" },
                        { "code": "LAW 418", "name": "Criminology & Penology (3 cr)" },
                        { "code": "LAW 419", "name": "International Criminal Law (3 cr)" },
                        { "code": "LAW 420", "name": "Medical Jurisprudence & Forensic Law (3 cr)" },
                        { "code": "LAW 418 (Alternate code)", "name": "Legal Drafting (Civil & Criminal) & Conveyance (4 cr)" },
                        { "code": "LAW 419 (Alternate)", "name": "Fiscal & Taxation Law (3 cr)" },
                        { "code": "LAW 420 (Alternate)", "name": "Clinical Legal Education & Community Legal Service (4 cr)" },
                        { "code": "LAW 421", "name": "Public International Law (3 cr)" },
                        { "code": "LAW 422", "name": "Environmental Law & Policy of Bangladesh (3 cr)" },
                        { "code": "LAW 423", "name": "Land Laws of Bangladesh (3 cr)" },
                        { "code": "LAW 424", "name": "Cyber, Media & Telecommunications Law (3 cr)" }
                    ]
                },
                {
                    "name": "Department of History & Philosophy",
                    "courses": [
                        { "code": "HIS 101", "name": "Bangladesh History & Culture" },
                        { "code": "PHI 101", "name": "Introduction to Philosophy" },
                        { "code": "PHI 104", "name": "Introduction to Ethics" },
                        { "code": "PHI 270", "name": "Philosophy of Science" },
                        { "code": "PHI 401", "name": "Business Ethics" },
                        { "code": "PSY 101", "name": "Introduction to Psychology" },
                        { "code": "PSY 101L", "name": "Introduction to Psychology Lab" },
                        { "code": "PSY 105", "name": "Elements of Psychology" },
                        { "code": "PSY 205", "name": "Introduction to World Religions" }
                    ]
                }
            ]
        }
    ]
};