export interface Course {
  code: string;
  name: string;
}

export interface Faculty {
  name: string;
  skills: string[];
  courses: Course[];
}

export interface School {
  name: string;
  faculties: Faculty[];
}

export const coursesData: { schools: School[] } = {
  schools: [
    {
      name: "SBE (School of Business and Economic)",
      faculties: [
        {
          name: "Department of Accounting & Finance",
          skills: [
            "Double-entry bookkeeping",
            "Preparing financial statements (Balance Sheet, Income Statement, Cash Flow)",
            "Journal entries & ledgers",
            "Accrual vs. cash accounting",
            "Basic GAAP principles",
            "Cost classification (fixed, variable, direct, indirect)",
            "Budgeting & forecasting",
            "Break-even analysis",
            "Performance measurement",
            "Variance analysis",
            "Advanced financial reporting",
            "Revenue recognition standards",
            "Accounting for assets (PPE, inventory, intangibles)",
            "Liabilities & contingencies",
            "Financial disclosures",
            "Accounting for pensions & leases",
            "Income taxes (deferred tax, temporary differences)",
            "Equity method investments",
            "Consolidations basics",
            "Cash flow complexities",
            "Strategic cost management",
            "Activity-based costing",
            "Balanced scorecard techniques",
            "Transfer pricing",
            "Advanced budgeting",
            "Personal & corporate tax structures",
            "Tax planning & compliance",
            "VAT & indirect taxes",
            "Tax return preparation",
            "Tax law interpretation",
            "Internal controls evaluation",
            "Audit risk & materiality",
            "Evidence gathering techniques",
            "Audit reporting",
            "Ethical standards in auditing",
            "Ratio analysis (liquidity, solvency, profitability)",
            "Trend & horizontal/vertical analysis",
            "Cash flow analysis",
            "Valuation techniques",
            "Credit analysis",
            "ERP systems (SAP, Oracle basics)",
            "Database management in accounting",
            "IT controls & auditing",
            "System documentation techniques",
            "Business process automation",
            "Business combinations & consolidations",
            "Foreign currency translation",
            "Partnership accounting",
            "Segment reporting",
            "Complex group structures",
            "Capital markets vs. money markets",
            "Role of central banks",
            "Securities & trading mechanisms",
            "Regulatory frameworks",
            "Risk in financial institutions",
            "Portfolio theory (Markowitz, CAPM)",
            "Efficient market hypothesis",
            "Asset pricing models",
            "Security valuation (stocks, bonds)",
            "Risk diversification",
            "Capital structure decisions",
            "Dividend policy",
            "Mergers & acquisitions",
            "Firm valuation",
            "Financing strategies",
            "Foreign exchange markets",
            "Currency risk hedging (forwards, options, swaps)",
            "Cross-border investments",
            "Global capital budgeting",
            "Multinational financing",
            "Excel financial functions (NPV, IRR, PMT)",
            "Sensitivity & scenario analysis",
            "Forecasting with spreadsheets",
            "Building valuation models",
            "Monte Carlo simulations",
            "Asset-liability management",
            "Credit risk analysis",
            "Liquidity management",
            "Basel accords compliance",
            "Interest rate risk",
            "Types of insurance products",
            "Risk identification & measurement",
            "Underwriting principles",
            "Actuarial basics",
            "Claims management",
            "Options, futures, forwards, swaps",
            "Hedging strategies",
            "Pricing models (Black-Scholes, binomial)",
            "Speculation vs. arbitrage",
            "Risk management using derivatives",
          ],
          courses: [
            {
              code: "ACT 201",
              name: "Introduction to Financial Accounting",
            },
            {
              code: "ACT 202",
              name: "Introduction to Managerial Accounting",
            },
            {
              code: "ACT 310",
              name: "Intermediate Accounting - I",
            },
            {
              code: "ACT 320",
              name: "Intermediate Accounting - II",
            },
            {
              code: "ACT 360",
              name: "Advanced Managerial Accounting",
            },
            {
              code: "ACT 370",
              name: "Taxation",
            },
            {
              code: "ACT 380",
              name: "Audit and Assurance",
            },
            {
              code: "ACT 410 / FIN 410",
              name: "Financial Statement Analysis",
            },
            {
              code: "ACT 430",
              name: "Accounting Information Systems",
            },
            {
              code: "ACT 460",
              name: "Advanced Financial Accounting",
            },
            {
              code: "FIN 254",
              name: "Introduction to Financial Management",
            },
            {
              code: "FIN 433",
              name: "Financial Markets & Institutions",
            },
            {
              code: "FIN 435",
              name: "Investment Theory",
            },
            {
              code: "FIN 440",
              name: "Corporate Finance",
            },
            {
              code: "FIN 444",
              name: "International Financial Management",
            },
            {
              code: "FIN 455",
              name: "Financial Modeling Using Excel",
            },
            {
              code: "FIN 464",
              name: "Bank Management",
            },
            {
              code: "FIN 470",
              name: "Insurance and Risk Management",
            },
            {
              code: "FIN 480",
              name: "Financial Derivatives",
            },
          ],
        },
        {
          name: "Department of Marketing & International Business",
          skills: [],
          courses: [
            { code: "MKT202", name: "Introduction to Marketing" },
            { code: "MKT337", name: "Promotional Management" },
            { code: "MKT344", name: "Consumer Behavior" },
            { code: "MKT460", name: "Strategic Marketing" },
            { code: "MKT470", name: "Marketing Research" },
            { code: "MKT330", name: "Digital Marketing" },
            { code: "MKT355", name: "Agricultural Marketing" },
            { code: "MKT382", name: "International Marketing" },
            { code: "MKT412", name: "Services Marketing" },
            { code: "MKT417", name: "Export Import Management" },
            { code: "MKT445", name: "Sales Management" },
            { code: "MKT450", name: "Marketing Channels" },
            { code: "MKT465", name: "Brand Management" },
            { code: "MKT475", name: "Marketing Analytics" },
          ],
        },
        {
          name: "Department of Management",
          skills: [],
          courses: [
            {
              code: "BUS 135",
              name: "Applied Business Mathematics",
            },
            { code: "BUS172", name: "Introduction to statistics" },
            { code: "BUS 173", name: "Applied statistics" },
            { code: "BUS 251", name: "Business Communication" },
            { code: "BUS 498", name: "Internship" },
            { code: "HRM 340", name: "Training and Development" },
            { code: "HRM 360", name: "Planning and Staffing" },
            {
              code: "HRM 370",
              name: "Leadership Theory and Practice",
            },
            { code: "HRM 380", name: "Compensation" },
            { code: "HRM 450", name: "Labor Management Relations" },
            { code: "HRM 470", name: "Negotiations" },
            { code: "MGT 212", name: "Organizational Management" },
            {
              code: "MGT 314",
              name: "Operations & Supply Chain Management",
            },
            { code: "MGT 321", name: "Organizational Behavior" },
            { code: "MGT 351", name: "Human Resource Management" },
            { code: "MGT 368", name: "Entrepreneurship" },
            {
              code: "MGT 330",
              name: "Designing Effective Organizations",
            },
            {
              code: "MGT 410",
              name: "Organizational Development and Change Management",
            },
            { code: "MGT 489", name: "Strategic Management" },
            { code: "MGT 490", name: "Project Management" },
            {
              code: "MIS 107",
              name: "Information System & Computing",
            },
            { code: "MIS 207", name: "E-Business" },
            {
              code: "MIS210",
              name: "Concepts of Computer Programming",
            },
            {
              code: "MIS310",
              name: "Database Systems for Business",
            },
            {
              code: "MIS320",
              name: "Digital Enterprise Management",
            },
            { code: "MIS410", name: "Business Intelligence" },
            {
              code: "MIS450",
              name: "Data Communication and Networking for Business",
            },
            { code: "MIS470", name: "Systems Analysis and Design" },
            {
              code: "SCM310",
              name: "Logistics and Transportation",
            },
            {
              code: "SCM 320",
              name: "Demand Planning and Fulfilment",
            },
            { code: "MGT/SCM 360", name: "Services Management" },
            {
              code: "SCM 450",
              name: "Global Procurement and Sourcing",
            },
          ],
        },
        {
          name: "Department of Economics",
          skills: ["Quantitative skills", "Analytical skills"],
          courses: [
            {
              code: "Eco101",
              name: "introduction to Microeconomics",
            },
            {
              code: "Eco 104",
              name: "principles of macroeconomics",
            },
            { code: "Eco172", name: "introduction to statistic" },
            { code: "Eco173", name: "applied statistic" },
            {
              code: "Eco201",
              name: "Intermediate Microeconomics Theory",
            },
            {
              code: "ECO204",
              name: "intermediate Macroeconomics theory",
            },
            { code: "Eco372", name: "introduction to economics" },
            { code: "Eco490", name: "senior seminer" },
            { code: "Eco317", name: "money and banking" },
            { code: "Eco328", name: "international economics" },
            { code: "Eco349", name: "economy of Bangladesh" },
            {
              code: "Eco354",
              name: "environmental & natural resources economics",
            },
            {
              code: "Eco496",
              name: "History of Economics thought",
            },
            { code: "Eco414", name: "Public Finance" },
            { code: "Eco441", name: "labor Economics" },
            { code: "Eco443", name: "health economics" },
            { code: "Eco415", name: "economic development" },
            { code: "Eco492", name: "special topic in economics" },
          ],
        },
      ],
    },
    {
      name: "SEPS (School of Engineering and Physical Science)",
      faculties: [
        {
          name: "Department of Architecture",
          skills: [
            "Sketching fundamentals",
            "Creative visualization",
            "Artistic expression in design",
            "Hand-eye coordination in drawing",
            "Conceptual thinking",
            "Principles of form (balance, symmetry, proportion)",
            "Composition in space",
            "Visual hierarchy in design",
            "Spatial arrangement",
            "Orthographic projection",
            "Perspective drawing",
            "Line weights & shading",
            "Freehand sketching",
            "Rendering techniques (pencil, ink, watercolor)",
            "Light & shadow representation",
            "Material texture rendering",
            "Presentation graphics",
            "AutoCAD basics",
            "Photoshop for architecture",
            "Digital rendering & visualization",
            "Presentation boards",
            "History of art & architecture",
            "Aesthetic principles",
            "Artistic critique",
            "Cultural symbolism in art",
            "Semiotics of images",
            "Relationship between words & visuals",
            "Visual culture analysis",
            "Principles of aesthetics",
            "Proportion systems (Golden Ratio, Modulor)",
            "Color theory in architecture",
            "Design evaluation methods",
            "Physical model-making",
            "Material handling (wood, clay, paper)",
            "Observational sketching",
            "Documentation of form",
            "Human scale & ergonomics",
            "Product design basics",
            "Prototyping methods",
            "Dimensional analysis",
            "Functional zoning",
            "Space analysis",
            "Bubble diagrams",
            "Design problem-solving",
            "Basic building layouts",
            "Circulation analysis",
            "Spatial programming",
            "Site response design",
            "History of global, Indian, Bengal, Islamic, and modern architecture",
            "Conservation principles",
            "Cultural heritage studies",
            "Comparative architectural history",
            "History of global, Indian, Bengal, Islamic, and modern architecture",
            "Conservation principles",
            "Cultural heritage studies",
            "Comparative architectural history",
            "Urban morphology",
            "Land use planning",
            "Environmental impact assessment",
            "Sustainable city design",
            "Climate-responsive design",
            "Building physics (heat, light, sound)",
            "HVAC systems",
            "Energy-efficient design integration",
            "Climate-responsive design",
            "Building physics (heat, light, sound)",
            "HVAC systems",
            "Energy-efficient design integration",
            "Building materials (steel, concrete, timber)",
            "Construction technology",
            "Workshop-based construction skills",
            "Detailing & joinery",
            "Building materials (steel, concrete, timber)",
            "Construction technology",
            "Workshop-based construction skills",
            "Detailing & joinery",
            "Building materials (steel, concrete, timber)",
            "Construction technology",
            "Workshop-based construction skills",
            "Detailing & joinery",
            "Structural systems (beam, truss, frame)",
            "Load transfer mechanisms",
            "Basic structural design",
            "Earthquake & wind load principles",
            "Structural systems (beam, truss, frame)",
            "Load transfer mechanisms",
            "Basic structural design",
            "Earthquake & wind load principles",
            "Structural systems (beam, truss, frame)",
            "Load transfer mechanisms",
            "Basic structural design",
            "Earthquake & wind load principles",
            "Multimedia tools in architecture",
            "Animation basics",
            "Architectural photography",
            "3D modeling",
            "Space planning for interiors",
            "Furniture design",
            "Lighting design",
            "Interior finishes",
            "Complex building functions",
            "Institutional & commercial design",
            "Project integration",
            "Design documentation",
            "Complex building functions",
            "Institutional & commercial design",
            "Project integration",
            "Design documentation",
            "Complex building functions",
            "Institutional & commercial design",
            "Project integration",
            "Design documentation",
            "Construction detailing",
            "Shop drawings",
            "Technical documentation",
            "Assembly drawings",
            "Design thinking methods",
            "Research in architecture",
            "Criticism & evaluation techniques",
            "Urban sociology",
            "Space & society interaction",
            "Public realm design",
            "Cultural geography",
            "History of global, Indian, Bengal, Islamic, and modern architecture",
            "Conservation principles",
            "Cultural heritage studies",
            "Comparative architectural history",
            "History of global, Indian, Bengal, Islamic, and modern architecture",
            "Conservation principles",
            "Cultural heritage studies",
            "Comparative architectural history",
            "History of global, Indian, Bengal, Islamic, and modern architecture",
            "Conservation principles",
            "Cultural heritage studies",
            "Comparative architectural history",
            "History of global, Indian, Bengal, Islamic, and modern architecture",
            "Conservation principles",
            "Cultural heritage studies",
            "Comparative architectural history",
            "History of global, Indian, Bengal, Islamic, and modern architecture",
            "Conservation principles",
            "Cultural heritage studies",
            "Comparative architectural history",
            "Tropical architecture principles",
            "Passive cooling",
            "Sustainable design in hot-humid climates",
            "Advanced structural systems",
            "Shell & space-frame structures",
            "High-rise design basics",
            "Landscape planning",
            "Plant selection & ecology",
            "Hardscape & softscape design",
            "Advanced design projects",
            "Multi-functional space planning",
            "Integration of technology in design",
            "Advanced design projects",
            "Multi-functional space planning",
            "Integration of technology in design",
            "Architectural codes & regulations",
            "Professional ethics",
            "Project delivery systems",
            "Client-architect relationships",
            "Ecological design principles",
            "Bioclimatic architecture",
            "Environmental psychology",
            "Project management",
            "Architectural firm management",
            "Cost estimation",
            "Contract administration",
            "Land use & transport planning",
            "Human settlement design",
            "Residential & non-residential building design",
            "Rural & urban development",
            "Land use & transport planning",
            "Human settlement design",
            "Residential & non-residential building design",
            "Rural & urban development",
            "Land use & transport planning",
            "Human settlement design",
            "Residential & non-residential building design",
            "Rural & urban development",
            "Land use & transport planning",
            "Human settlement design",
            "Residential & non-residential building design",
            "Rural & urban development",
            "Land use & transport planning",
            "Human settlement design",
            "Residential & non-residential building design",
            "Rural & urban development",
            "Land use & transport planning",
            "Human settlement design",
            "Residential & non-residential building design",
            "Rural & urban development",
            "Ecological design principles",
            "Bioclimatic architecture",
            "Environmental psychology",
            "Construction documentation",
            "Field surveying",
            "Measured drawings",
            "Construction documentation",
            "Field surveying",
            "Measured drawings",
            "Advanced load analysis",
            "Innovative structural systems",
            "Parametric structural design",
            "Advanced load analysis",
            "Innovative structural systems",
            "Parametric structural design",
            "Building automation",
            "Smart buildings",
            "Construction economics",
            "Safety & security systems",
            "Building automation",
            "Smart buildings",
            "Construction economics",
            "Safety & security systems",
            "Building automation",
            "Smart buildings",
            "Construction economics",
            "Safety & security systems",
            "Building automation",
            "Smart buildings",
            "Construction economics",
            "Safety & security systems",
            "Land use & transport planning",
            "Human settlement design",
            "Land use & transport planning",
            "Human settlement design",
            "Residential & non-residential building design",
            "Rural & urban development",
            "Residential & non-residential building design",
            "Rural & urban development",
            "Research methodology in architecture",
            "Academic writing & documentation",
            "Seminar presentation skills",
            "Design thesis execution",
            "Research methodology in architecture",
            "Academic writing & documentation",
            "Seminar presentation skills",
            "Design thesis execution",
            "Research methodology in architecture",
            "Academic writing & documentation",
            "Seminar presentation skills",
            "Design thesis execution",
          ],
          courses: [
            {
              code: "ARC 111",
              name: "Foundation Design Studio I- Artistic Development",
            },
            {
              code: "ARC 112",
              name: "Foundation Design Studio II- Form and Composition",
            },
            {
              code: "ARC 121",
              name: "Graphics I- Basic Drawing",
            },
            {
              code: "ARC 122",
              name: "Graphics II- Rendering",
            },
            {
              code: "ARC 123",
              name: "Graphics III- Digital Presentation",
            },
            {
              code: "ARC 131",
              name: "Sources in Architecture I- Artistic Appreciation",
            },
            {
              code: "ARC 132",
              name: "Sources in Architecture II- Introduction to Visual Studies, Word and Images",
            },
            {
              code: "ARC 133:1",
              name: "Parameters in Design I- Aesthetic and Design",
            },
            {
              code: "ARC 200",
              name: "Craft and Design- Observation and Documentation",
            },
            {
              code: "ARC 213",
              name: "Allied Design Studio- Dimension and Product",
            },
            {
              code: "ARC 214",
              name: "Architecture Design Studio I- Function and Analysis",
            },
            {
              code: "ARC 215",
              name: "Architecture Design Studio II- Simple Function",
            },
            {
              code: "ARC 241",
              name: "Architectural Heritage I- World I",
            },
            {
              code: "ARC 242",
              name: "Architectural Heritage II- World II",
            },
            {
              code: "ARC 251",
              name: "Introduction to Urban Design and Environmental Planning",
            },
            {
              code: "ARC 261",
              name: "Environment and Building System I- Climate and Design",
            },
            {
              code: "ARC 262",
              name: "Environment and Building System II- Building Physics",
            },
            {
              code: "ARC 263",
              name: "Environment and Building System III- Building Services",
            },
            {
              code: "ARC 264",
              name: "Environment and Building System IV- Design Integration",
            },
            {
              code: "ARC 271",
              name: "Construction I- Materials",
            },
            {
              code: "ARC 272",
              name: "Construction II- Technology",
            },
            {
              code: "ARC 273",
              name: "Construction III- Workshop",
            },
            {
              code: "ARC 281",
              name: "Building Structures I: Basic Principles",
            },
            {
              code: "ARC 282",
              name: "Building Structures II",
            },
            {
              code: "ARC 283",
              name: "Building Structures III",
            },
            {
              code: "ARC 293",
              name: "Design-Related-Media",
            },
            {
              code: "ARC 310",
              name: "Interior Design Studio",
            },
            {
              code: "ARC 316",
              name: "Professional Studies Studio I- Form and Function",
            },
            {
              code: "ARC 317",
              name: "Professional Studies Studio II- Complex Function",
            },
            {
              code: "ARC 318",
              name: "Professional Studies Studio III- Complex Function",
            },
            {
              code: "ARC 324",
              name: "Graphics IV-Working Details",
            },
            {
              code: "ARC 334",
              name: "Parameters in Design II- Theory and Methods",
            },
            {
              code: "ARC 336",
              name: "Architecture and Urbanism- Space, Culture and Urban Design",
            },
            {
              code: "ARC 343",
              name: "Architectural Heritage III- India",
            },
            {
              code: "ARC 344",
              name: "Architectural Heritage IV- Bengal",
            },
            {
              code: "ARC 346",
              name: "Architectural Heritage V- Contemporary South and Southeast Asia",
            },
            {
              code: "ARC 347",
              name: "Architectural Heritage VI- Islamic",
            },
            {
              code: "ARC 348",
              name: "Built Heritage and Conservation",
            },
            {
              code: "ARC 365",
              name: "Design for the Tropics",
            },
            {
              code: "ARC 384",
              name: "Building Structures IV",
            },
            {
              code: "ARC 394",
              name: "Special Topic I (Technology, Environment or Science)",
            },
            {
              code: "ARC 410",
              name: "Landscape Design Laboratory",
            },
            {
              code: "ARC 418",
              name: "Design and Allied Studies Studio I",
            },
            {
              code: "ARC 419",
              name: "Design and Allied Studies Studio II",
            },
            {
              code: "ARC 436",
              name: "Buildings, Land, and Cultural Traditions- Diversity and Change",
            },
            {
              code: "ARC 437",
              name: "Professional Practice, Ethics and Society",
            },
            {
              code: "ARC 438",
              name: "Environmental Psychology",
            },
            {
              code: "ARC 439",
              name: "Management and Business Administration in Architecture",
            },
            {
              code: "ARC 445",
              name: "Contemporary Design- Precedents and Analyses",
            },
            {
              code: "ARC 452",
              name: "Land-Use, Infrastructure and Transport Planning",
            },
            {
              code: "ARC 453",
              name: "Human Settlement- Policy and Planning",
            },
            {
              code: "ARC 454",
              name: "Human Geography- Settlement and Development",
            },
            {
              code: "ARC 455",
              name: "Advanced Urban Design and Planning Applications",
            },
            {
              code: "ARC 456",
              name: "Rural Studies",
            },
            {
              code: "ARC 457",
              name: "Urbanism and Local Context",
            },
            {
              code: "ARC 458",
              name: "Residential Building Design",
            },
            {
              code: "ARC 459",
              name: "Non-Residential Building Design",
            },
            {
              code: "ARC 466",
              name: "Ecology and Bio-Climatic Design",
            },
            {
              code: "ARC 474",
              name: "Construction IV- Documents and Management",
            },
            {
              code: "ARC 475",
              name: "Field Survey, Measured Drawing and Documentation",
            },
            {
              code: "ARC 485",
              name: "Advanced Architectural Structure I",
            },
            {
              code: "ARC 486",
              name: "Advanced Architectural Structure II",
            },
            { code: "ARC 492", name: "Independent Study" },
            {
              code: "ARC 495",
              name: "Special Topic II (Design, Theory or Settlement)",
            },
            {
              code: "ARC 500",
              name: "Professional Internship (supervised training)",
            },
            { code: "ARC 510", name: "Advanced Studies Studio I" },
            {
              code: "ARC 519",
              name: "Advanced Studies Studio II- Thesis Project",
            },
            {
              code: "ARC 535",
              name: "Parameters in Design III- Pedagogy and Discourse",
            },
            {
              code: "ARC 576",
              name: "Building Automation and Hi-Tech Architecture",
            },
            {
              code: "ARC 577",
              name: "Building Systems Integration",
            },
            {
              code: "ARC 578",
              name: "Building Economics",
            },
            {
              code: "ARC 579",
              name: "Building Safety and Security",
            },
            {
              code: "ARC 596",
              name: "Thesis Documentation- Research and Development",
            },
            {
              code: "ARC 597",
              name: "Methods of Inquiry on Architecture, City and Environment",
            },
            {
              code: "ARC 598",
              name: "Seminar on Art, Architecture, Society and Culture",
            },
          ],
        },
        {
          name: "Department of Civil & Environmental Engineering",
          skills: [
            "Structural analysis methods",
            "Beam and frame analysis",
            "Load calculation",
            "Structural design principles",
            "Structural analysis software",
            "Experimental testing",
            "Data analysis",
            "Lab report writing",
            "Advanced structural analysis",
            "Matrix methods",
            "Indeterminate structures",
            "Computer analysis",
            "Advanced structural testing",
            "Computer modeling",
            "Design verification",
            "Technical documentation",
            "Concrete properties",
            "Reinforcement design",
            "Beam design",
            "Slab design",
            "Concrete mixing and testing",
            "Reinforcement detailing",
            "Design calculations",
            "Construction practices",
            "Advanced concrete design",
            "Column design",
            "Foundation design",
            "Seismic design",
            "Soil classification",
            "Soil testing",
            "Foundation design",
            "Bearing capacity analysis",
            "Soil testing procedures",
            "Laboratory equipment use",
            "Data collection and analysis",
            "Soil report preparation",
            "Deep foundation design",
            "Pile analysis",
            "Retaining structures",
            "Ground improvement",
            "Traffic analysis",
            "Transportation planning",
            "Highway design",
            "Safety evaluation",
            "Traffic data collection",
            "Surveying techniques",
            "Transportation software",
            "Lab report writing",
            "Traffic flow theory",
            "Capacity analysis",
            "Signal design",
            "Traffic simulation",
            "Open channel flow analysis",
            "Hydraulic design",
            "Flow measurement",
            "Energy principles",
            "Hydraulic experiments",
            "Flow measurement techniques",
            "Data analysis",
            "Lab report preparation",
            "Groundwater flow analysis",
            "Well hydraulics",
            "Aquifer testing",
            "Groundwater modeling",
            "Water quality analysis",
            "Treatment processes",
            "Distribution systems",
            "Water treatment plant design",
            "Water quality testing",
            "Treatment process experiments",
            "Lab equipment operation",
            "Water analysis reporting",
            "Wastewater collection",
            "Treatment processes",
            "Sludge handling",
            "Wastewater treatment plant design",
            "Wastewater analysis",
            "Treatment process testing",
            "Lab procedures",
            "Environmental monitoring",
            "EIA procedures",
            "Environmental monitoring",
            "Impact analysis",
            "Mitigation strategies",
            "Waste characterization",
            "Collection systems",
            "Treatment technologies",
            "Hazardous waste management",
            "Project planning",
            "Design development",
            "Technical documentation",
            "Team collaboration",
            "Project implementation",
            "Design optimization",
            "Quality control",
            "Project reporting",
            "Project completion",
            "Performance evaluation",
            "Final documentation",
            "Presentation skills",
            "Dynamic analysis",
            "Vibration analysis",
            "Response spectra",
            "Earthquake engineering",
            "Composite materials",
            "Fiber-reinforced polymers",
            "Design principles",
            "Failure analysis",
            "Finite element theory",
            "Modeling techniques",
            "Software applications",
            "Result interpretation",
            "Advanced concrete behavior",
            "Special design cases",
            "Code provisions",
            "Seismic design",
            "Prestressing methods",
            "Loss calculations",
            "Design of prestressed members",
            "Construction practices",
            "Steel design principles",
            "Connection design",
            "Stability analysis",
            "Load combinations",
            "Seismic analysis",
            "Building codes",
            "Dynamic response",
            "Design for earthquake resistance",
            "Advanced soil mechanics",
            "Foundation analysis",
            "Slope stability",
            "Geotechnical modeling",
            "Dam design principles",
            "Slope analysis",
            "Stability assessment",
            "Risk evaluation",
            "Retaining wall design",
            "Lateral earth pressure",
            "Stability analysis",
            "Construction methods",
            "Advanced soil behavior",
            "Laboratory testing",
            "Numerical modeling",
            "Problem solving",
            "Safety analysis",
            "Accident investigation",
            "Safety design",
            "Risk assessment",
            "Pavement materials",
            "Design methods",
            "Construction practices",
            "Performance evaluation",
            "Traffic flow theory",
            "Intelligent transportation systems",
            "Traffic management",
            "Simulation modeling",
            "Transportation planning",
            "Systems analysis",
            "Network design",
            "Policy evaluation",
            "Road geometry",
            "Design standards",
            "Sight distance analysis",
            "Horizontal and vertical alignment",
            "Water resources planning",
            "Integrated management",
            "Policy development",
            "Sustainability assessment",
            "River hydraulics",
            "Sediment transport",
            "River training",
            "Flood control",
            "Irrigation systems",
            "Drainage design",
            "Water management",
            "Agricultural water use",
            "Coastal processes",
            "Wave mechanics",
            "Tidal analysis",
            "Coastal protection",
            "Hydrological modeling",
            "Water quality modeling",
            "Software applications",
            "Model calibration",
          ],
          courses: [
            {
              code: "CEE 100",
              name: "Introduction to Civil & Environmental Engineering",
            },
            {
              code: "CEE 110",
              name: "Computer-Aided Drawing (CAD) for Engineers",
            },
            {
              code: "CEE 330",
              name: "Structural Analysis & Design I",
            },
            {
              code: "CEE 330L",
              name: "Structural Analysis & Design Lab",
            },
            {
              code: "CEE 331",
              name: "Structural Analysis & Design II",
            },
            {
              code: "CEE 331L",
              name: "Structural Analysis & Design Lab (II)",
            },
            {
              code: "CEE 335",
              name: "Reinforced Concrete Design I",
            },
            {
              code: "CEE 335L",
              name: "Reinforced Concrete Design Lab",
            },
            {
              code: "CEE 430",
              name: "Reinforced Concrete Design II",
            },
            {
              code: "CEE 240",
              name: "Intro to Soil Mechanics & Foundation Engineering",
            },
            {
              code: "CEE 240L",
              name: "Soil Mechanics Lab",
            },
            {
              code: "CEE 340",
              name: "Advanced Foundation Engineering",
            },
            {
              code: "CEE 250",
              name: "Intro to Transportation Engineering",
            },
            {
              code: "CEE 250L",
              name: "Transportation Engineering Lab",
            },
            {
              code: "CEE 350",
              name: "Traffic Analysis & Design",
            },
            {
              code: "CEE 360",
              name: "Open‑Channel Hydraulics",
            },
            {
              code: "CEE 360L",
              name: "Open‑Channel Hydraulics Lab",
            },
            {
              code: "CEE 460",
              name: "Groundwater Hydraulics",
            },
            {
              code: "CEE 370",
              name: "Water Supply & Treatment",
            },
            {
              code: "CEE 370L",
              name: "Lab: Water Supply & Treatment",
            },
            {
              code: "CEE 373",
              name: "Sanitation & Wastewater Engineering",
            },
            {
              code: "CEE 373L",
              name: "Sanitation & Wastewater Engineering Lab",
            },
            {
              code: "ENV 373",
              name: "Environmental Impact Assessment",
            },
            {
              code: "CEE 470",
              name: "Solid & Hazardous Waste Engineering",
            },
            {
              code: "CEE 499A",
              name: "Engineering Project I",
            },
            {
              code: "CEE 499B",
              name: "Engineering Project II",
            },
            {
              code: "CEE 499C",
              name: "Engineering Project III",
            },
            {
              code: "CEE 498",
              name: "Co‑op / Internship (mandatory, zero credit)",
            },
            {
              code: "CEE 431",
              name: "Intro to Structural Dynamics",
            },
            {
              code: "CEE 432",
              name: "Composite Structures",
            },
            {
              code: "CEE 433",
              name: "Finite Element Methods",
            },
            {
              code: "CEE 434",
              name: "Advanced Reinforced Concrete Design",
            },
            {
              code: "CEE 435",
              name: "Prestressed Concrete",
            },
            {
              code: "CEE 437",
              name: "Behavior & Design of Metal Structures",
            },
            {
              code: "CEE 439",
              name: "Earthquake‑Resistant Design",
            },
            {
              code: "CEE 441",
              name: "Advanced Geotechnical Engineering",
            },
            {
              code: "CEE 442",
              name: "Earthen Dam & Slope Stability",
            },
            {
              code: "CEE 443",
              name: "Earth Retaining Structures",
            },
            {
              code: "CEE 444",
              name: "Advanced Soil Mechanics",
            },
            {
              code: "CEE 450",
              name: "Road & Traffic Safety Engineering",
            },
            {
              code: "CEE 452",
              name: "Pavement Analysis, Design & Construction",
            },
            {
              code: "CEE 454",
              name: "Advanced Traffic Engineering",
            },
            {
              code: "CEE 458",
              name: "Transportation Systems Engineering & Planning",
            },
            {
              code: "CEE 459",
              name: "Geometric Analysis & Design of Roads",
            },
            {
              code: "CEE 463",
              name: "Integrated Water Resources Planning & Management",
            },
            {
              code: "CEE 465",
              name: "River Engineering",
            },
            {
              code: "CEE 467",
              name: "Irrigation & Drainage Engineering",
            },
            {
              code: "CEE 473",
              name: "Coastal & Estuarine Analysis",
            },
            {
              code: "CEE 475",
              name: "Water Resources & Environmental Modeling",
            },
          ],
        },
        {
          name: "Department of Electrical & Computer Engineering",
          skills: [
            "Basic circuit analysis",
            "Ohm's law",
            "Kirchhoff's laws",
            "Network theorems",
            "AC circuit analysis",
            "Phasor analysis",
            "Frequency response",
            "Three-phase circuits",
            "Diode applications",
            "Transistor biasing",
            "Amplifier design",
            "Operational amplifiers",
            "Boolean algebra",
            "Logic gate design",
            "Combinational circuits",
            "Sequential circuits",
            "Advanced amplifier design",
            "Feedback amplifiers",
            "Oscillators",
            "Power amplifiers",
            "Signal classification",
            "Fourier analysis",
            "Laplace transforms",
            "System response",
            "Electrostatics",
            "Magnetostatics",
            "Maxwell's equations",
            "Wave propagation",
            "Control system modeling",
            "Transfer functions",
            "Stability analysis",
            "Controller design",
            "DC machines",
            "Transformers",
            "Induction motors",
            "Synchronous machines",
            "Power semiconductor devices",
            "Rectifiers",
            "Inverters",
            "DC-DC converters",
            "Power generation",
            "Transmission lines",
            "Power distribution",
            "Load flow analysis",
            "Analog modulation",
            "Digital modulation",
            "Noise analysis",
            "Communication system design",
            "Cost analysis",
            "Investment evaluation",
            "Project planning",
            "Financial decision making",
            "Project planning",
            "Design implementation",
            "Technical documentation",
            "Team collaboration",
            "Advanced project design",
            "System integration",
            "Prototype development",
            "Final presentation",
            "Academic writing basics",
            "Grammar & sentence structure",
            "Paragraph organization",
            "Clarity & coherence in writing",
            "Essay structure (intro, body, conclusion)",
            "Argument construction",
            "Revision & editing techniques",
            "Writing with evidence",
            "Speech organization",
            "Voice control & articulation",
            "Presentation skills",
            "Audience engagement",
            "Programming fundamentals",
            "Algorithm design",
            "Debugging techniques",
            "Code documentation",
            "Basic electronics",
            "Circuit construction",
            "Measurement techniques",
            "Lab report writing",
            "Programming languages",
            "Data structures",
            "Software development",
            "Problem solving",
            "Analog circuit design",
            "Amplifier analysis",
            "Filter design",
            "Oscillator circuits",
            "Digital circuit design",
            "Logic optimization",
            "FPGA programming",
            "Hardware description languages",
            "Signal processing",
            "System analysis",
            "Transform methods",
            "Filter design",
            "Circuit analysis",
            "Measurement techniques",
            "Network theorems",
            "Experimental validation",
            "Project design",
            "Prototype development",
            "Testing procedures",
            "Technical documentation",
            "Digital circuit design",
            "Pulse circuit analysis",
            "Timing analysis",
            "Digital troubleshooting",
            "Communication system design",
            "Modulation techniques",
            "Signal analysis",
            "System testing",
            "Network protocols",
            "Data transmission",
            "Network security",
            "Network troubleshooting",
            "Microprocessor architecture",
            "Assembly language programming",
            "Interface design",
            "Embedded systems",
            "AC circuit analysis",
            "Frequency response",
            "Power measurements",
            "Circuit simulation",
            "Field theory",
            "Wave propagation",
            "Transmission lines",
            "Antenna theory",
            "Advanced project design",
            "System integration",
            "Performance testing",
            "Design optimization",
            "Semiconductor physics",
            "Device operation",
            "Fabrication processes",
            "Device characterization",
            "VLSI design",
            "CMOS technology",
            "Layout design",
            "Simulation tools",
            "Digital modulation",
            "Error correction",
            "Channel coding",
            "Receiver design",
            "Telecom protocols",
            "Network architecture",
            "Traffic analysis",
            "Network management",
            "Wireless standards",
            "Mobile network design",
            "RF measurements",
            "Network optimization",
            "Fiber optic principles",
            "Optical components",
            "Link design",
            "Performance testing",
            "DSP algorithms",
            "Filter design",
            "Spectral analysis",
            "Real-time processing",
            "Advanced communication systems",
            "System design",
            "Performance evaluation",
            "Research methodology",
            "Project management",
            "Research skills",
            "Technical presentation",
            "Professional development",
            "Power converter design",
            "Switching devices",
            "Control techniques",
            "Power quality",
            "AI algorithms",
            "Machine learning",
            "Neural networks",
            "Expert systems",
            "Web development",
            "Internet protocols",
            "Database integration",
            "Web security",
            "VoIP protocols",
            "Network design",
            "Quality of service",
            "System integration",
            "Image enhancement",
            "Pattern recognition",
            "Computer vision",
            "Image compression",
            "Computing fundamentals",
            "Problem solving",
            "Algorithmic thinking",
            "Basic programming",
            "Hands-on programming",
            "Debugging skills",
            "Software tools",
            "Lab practices",
            "Programming concepts",
            "Control structures",
            "Functions and procedures",
            "Data types",
            "Mathematical logic",
            "Set theory",
            "Combinatorics",
            "Graph theory",
            "Data organization",
            "Algorithm complexity",
            "Tree structures",
            "Graph algorithms",
            "Boolean algebra",
            "Combinational logic",
            "Sequential logic",
            "Digital design",
            "Computer architecture",
            "Processor design",
            "Memory hierarchy",
            "Input/output systems",
            "Circuit analysis",
            "Electronic components",
            "Measurement techniques",
            "Lab instrumentation",
            "Basic electronics",
            "Diode circuits",
            "Transistor applications",
            "Amplifier design",
          ],
          courses: [
            {
              code: "EEE 141 + CL",
              name: "Electrical Circuits I",
            },
            {
              code: "EEE 241 + CL",
              name: "Electrical Circuits II",
            },
            {
              code: "EEE 111 + CL",
              name: "Analog Electronics I",
            },
            {
              code: "EEE 211 + IL",
              name: "Digital Logic Design",
            },
            {
              code: "EEE 311 + CL",
              name: "Analog Electronics II",
            },
            {
              code: "EEE 221",
              name: "Signals & Systems",
            },
            {
              code: "EEE 361",
              name: "Electromagnetic Fields & Waves",
            },
            {
              code: "EEE 342 + CL",
              name: "Control Engineering",
            },
            {
              code: "EEE 363 + CL",
              name: "Electrical Machines",
            },
            {
              code: "EEE 312",
              name: "Power Electronics",
            },
            {
              code: "EEE 362",
              name: "Power Systems",
            },
            {
              code: "EEE 321 + IL",
              name: "Introduction to Communication Systems",
            },
            {
              code: "EEE 452",
              name: "Engineering Economics",
            },
            {
              code: "EEE 299",
              name: "Junior Design Project (1 credit)",
            },
            {
              code: "EEE 499A / 499B",
              name: "Senior Design I & II (1.5 credits each)",
            },
            {
              code: "EEE 498 (or 498R)",
              name: "Co-Op / Internship / Directed Research (non-credit)",
            },
            {
              code: "ENG 102",
              name: "English courses",
            },
            {
              code: "ENG 103",
              name: "English courses",
            },
            {
              code: "ENG 111",
              name: "English courses",
            },
            { code: "ENG 115", name: "English courses" },
            { code: "PHI 104", name: "Ethics" },
            {
              code: "HIS 101 / 102",
              name: "Humanities & Social Sciences",
            },
            {
              code: "SOC 101 / ANT 101 / ENV 203 / GEO 205",
              name: "Humanities & Social Sciences",
            },
            {
              code: "POL 101 / 104",
              name: "Humanities & Social Sciences",
            },
            {
              code: "ECO 101 / 104",
              name: "Humanities & Social Sciences",
            },
            { code: "MAT 116", name: "Calculus & Linear Algebra" },
            { code: "MAT 120", name: "Calculus & Linear Algebra" },
            { code: "MAT 125", name: "Calculus & Linear Algebra" },
            { code: "MAT 130", name: "Calculus & Linear Algebra" },
            { code: "MAT 250", name: "Calculus & Linear Algebra" },
            { code: "MAT 350", name: "Calculus & Linear Algebra" },
            { code: "MAT 361", name: "Calculus & Linear Algebra" },
            { code: "PHY 107+CL", name: "Science with Lab" },
            { code: "PHY 108+CL", name: "Science with Lab" },
            { code: "CHE 101+CL", name: "Science with Lab" },
            { code: "BIO 103+CL", name: "Science with Lab" },
            {
              code: "CSE 115 + CL",
              name: "Programming Language I",
            },
            {
              code: "ETE 131 + ETE131L",
              name: "Introduction to Telecommunication & Computer Engineering (lab)",
            },
            {
              code: "ETE 132",
              name: "Computer Programming (with lab)",
            },
            {
              code: "ETE 211",
              name: "Analog Electronics (with lab)",
            },
            {
              code: "ETE 212",
              name: "Digital Logic Design (with lab)",
            },
            {
              code: "ETE 221",
              name: "Signals & Systems",
            },
            {
              code: "ETE 241",
              name: "Electrical Circuits I (with lab)",
            },
            {
              code: "ETE 283",
              name: "Design Lab I",
            },
            {
              code: "ETE 311",
              name: "Digital Electronics & Pulse Techniques (lab)",
            },
            {
              code: "ETE 321",
              name: "Introduction to Communication Systems (lab)",
            },
            {
              code: "ETE 331",
              name: "Data Communications & Computer Networks (lab)",
            },
            {
              code: "ETE 332",
              name: "Microprocessors & Assembly Language (lab)",
            },
            {
              code: "ETE 341",
              name: "Electrical Circuits II (lab)",
            },
            {
              code: "ETE 361",
              name: "Electromagnetic Field Theory",
            },
            {
              code: "ETE 383",
              name: "Design Lab II",
            },
            {
              code: "ETE 411",
              name: "Semiconductor Devices & Technology",
            },
            {
              code: "ETE 412",
              name: "Introduction to VLSI (lab)",
            },
            {
              code: "ETE 422",
              name: "Principles of Digital Communications",
            },
            {
              code: "ETE 423",
              name: "Telecom Networks",
            },
            {
              code: "ETE 424",
              name: "Mobile & Wireless Communications (lab)",
            },
            {
              code: "ETE 426",
              name: "Fiber Optic Communications (lab)",
            },
            {
              code: "ETE 471",
              name: "Digital Signal Processing (lab)",
            },
            {
              code: "ETE 481 / 482",
              name: "Advanced Comm Lab I & II",
            },
            {
              code: "ETE 498 / 499",
              name: "Senior Project/Internship (3 credits)",
            },
            {
              code: "ETE 312",
              name: "Power Electronics",
            },
            {
              code: "ETE 333",
              name: "Artificial Intelligence",
            },
            {
              code: "ETE 334",
              name: "Internet & Web Technology",
            },
            {
              code: "ETE 406",
              name: "IP Telephony",
            },
            {
              code: "ETE 473",
              name: "Image Processing",
            },
            {
              code: "ETE 400",
              name: "Special Topics",
            },
            {
              code: "CSE 115",
              name: "Computing Concepts + Lab",
            },
            {
              code: "CSE 115L",
              name: "Computing Concepts + Lab",
            },
            {
              code: "CSE 135 + 135L",
              name: "Programming fundamentals",
            },
            {
              code: "CSE 173",
              name: "Discrete Math",
            },
            {
              code: "CSE 225 + IL",
              name: "Data Structures & Lab",
            },
            {
              code: "CSE 231 + IL",
              name: "Digital Logic",
            },
            {
              code: "CSE 232",
              name: "Computer Organization & Design",
            },
            {
              code: "CSE 243 + 243L",
              name: "Electrical Circuits + Lab",
            },
            {
              code: "CSE 253 + 253L",
              name: "Electronics I + Lab",
            },
            { code: "CSE  311", name: "CSE 311" },
            { code: "CSE 323", name: "CSE 323" },
            { code: "CSE 373", name: "CSE 373" },
          ],
        },
        {
          name: "Department of Mathematics & Physics",
          skills: [
            "Basic mathematical operations",
            "Percentage calculations",
            "Simple and compound interest",
            "Business applications",
            "Algebraic functions",
            "Trigonometric functions",
            "Exponential and logarithmic functions",
            "Graphing techniques",
            "Limits and continuity",
            "Differentiation techniques",
            "Applications of derivatives",
            "Graphing functions",
            "Matrix operations",
            "Determinants",
            "Vector spaces",
            "Linear transformations",
            "Integration techniques",
            "Applications of integration",
            "Sequences and series",
            "Parametric equations",
            "Multivariable calculus",
            "Partial derivatives",
            "Multiple integrals",
            "Vector calculus",
            "Advanced integration techniques",
            "Differential equations",
            "Series solutions",
            "Special functions",
            "Advanced calculus",
            "Differential equations",
            "Complex analysis",
            "Numerical methods",
            "Probability theory",
            "Statistical distributions",
            "Hypothesis testing",
            "Regression analysis",
            "Real number systems",
            "Sequences and series",
            "Continuity and differentiability",
            "Riemann integration",
            "First-order equations",
            "Second-order equations",
            "Systems of equations",
            "Laplace transforms",
            "Numerical differentiation",
            "Numerical integration",
            "Root finding algorithms",
            "Numerical solutions of equations",
            "Complex numbers",
            "Analytic functions",
            "Complex integration",
            "Residue theorem",
            "Control systems",
            "State-space methods",
            "Stability analysis",
            "Optimal control",
            "Linear programming",
            "Network analysis",
            "Queuing theory",
            "Decision analysis",
            "Advanced differential equations",
            "Partial differential equations",
            "Fourier analysis",
            "Special functions",
            "Group theory",
            "Ring theory",
            "Field theory",
            "Galois theory",
            "Mechanics",
            "Thermodynamics",
            "Wave motion",
            "Basic laboratory techniques",
            "Experimental techniques",
            "Data collection",
            "Error analysis",
            "Lab report writing",
            "Classical mechanics",
            "Newton's laws",
            "Energy and momentum",
            "Rotational motion",
            "Mechanics experiments",
            "Measurement techniques",
            "Data analysis",
            "Scientific reporting",
            "Electromagnetism",
            "Electric fields",
            "Magnetic fields",
            "Electromagnetic waves",
            "Electricity experiments",
            "Magnetism experiments",
            "Circuit analysis",
            "Instrumentation",
            "Elastic properties",
            "Thermal properties",
            "Mechanical properties",
            "Phase transitions",
            "Simple harmonic motion",
            "Wave equations",
            "Interference and diffraction",
            "Standing waves",
            "Special relativity",
            "Quantum mechanics basics",
            "Atomic structure",
            "Photoelectric effect",
            "Kinetic theory",
            "Laws of thermodynamics",
            "Heat engines",
            "Statistical mechanics",
            "Diode circuits",
            "Transistor amplifiers",
            "Operational amplifiers",
            "Digital circuits",
            "Nuclear physics",
            "Particle physics",
            "Quantum mechanics",
            "Solid state physics",
            "Numerical methods",
            "Simulation techniques",
            "Data analysis",
            "Programming for physics",
            "Medical imaging",
            "Radiation physics",
            "Biomechanics",
            "Medical instrumentation",
            "Nanoscale physics",
            "Nanomaterials",
            "Nanofabrication",
            "Applications of nanotechnology",
            "Basic mathematics",
            "Fundamental physics",
            "Problem solving",
            "Scientific methods",
            "Probability distributions",
            "Statistical inference",
            "Hypothesis testing",
            "Regression analysis",
            "Matrix algebra",
            "Vector operations",
            "Eigenvalues and eigenvectors",
            "Linear transformations",
            "Ordinary differential equations",
            "Partial differential equations",
            "Orthogonal functions",
            "Boundary value problems",
          ],
          courses: [
            {
              code: "Bus112",
              name: "Introduction to Business Mathematics",
            },
            {
              code: "MAT 116",
              name: "Pre-calculus",
            },
            {
              code: "MAT 120",
              name: "Calculus and Analytic Geometry- I",
            },
            {
              code: "MAT 125",
              name: "Introduction to Linear Algebra",
            },
            {
              code: "MAT 130",
              name: "Calculus and Analytic Geometry II",
            },
            {
              code: "MAT240",
              name: "Calculus and Analytic Geometry III",
            },
            {
              code: "MAT250",
              name: "Calculus and Analytic Geometry IV",
            },
            {
              code: "MAT350",
              name: "Engineering Mathematics",
            },
            {
              code: "MAT361",
              name: "Probability and Statistics",
            },
            {
              code: "MAT370",
              name: "Real Analysis",
            },
            {
              code: "MAT480",
              name: "Differential Equations",
            },
            {
              code: "MAT481",
              name: "Numerical Methods",
            },
            {
              code: "MAT482",
              name: "Complex Variables and Its Applications",
            },
            {
              code: "MAT483",
              name: "Mathematical Control Theory and Applications",
            },
            {
              code: "MAT485",
              name: "Operations Research",
            },
            {
              code: "MAT490",
              name: "Advanced Engineering Mathematics",
            },
            {
              code: "MAT495",
              name: "Abstract Algebra",
            },
            {
              code: "PHY105",
              name: "Fundamentals of Physics",
            },
            {
              code: "PHY105L",
              name: "Lab of Fundamentals of Physics",
            },
            {
              code: "PHY107",
              name: "General Physics I",
            },
            {
              code: "PHY107L",
              name: "Physics I Lab",
            },
            {
              code: "PHY108",
              name: "General Physics II",
            },
            {
              code: "PHY108L",
              name: "General Physics II Lab",
            },
            {
              code: "PHY230",
              name: "Properties of Matter",
            },
            {
              code: "PHY240",
              name: "Waves and Oscillations",
            },
            {
              code: "PHY250",
              name: "Modern Physics I",
            },
            {
              code: "PHY260",
              name: "Thermal Physics",
            },
            {
              code: "PHY335",
              name: "Electronic Circuits",
            },
            {
              code: "PHY350",
              name: "Modern Physics II",
            },
            {
              code: "PHY360",
              name: "Computational Physics",
            },
            {
              code: "PHY370",
              name: "Biomedical Physics",
            },
            {
              code: "PHY380",
              name: "Nanotechnology",
            },
            {
              code: "BSC201",
              name: "Basic Science Support- Math and Physics",
            },
            {
              code: "MAT140",
              name: "Introduction to Probability and Statistics for Engineers",
            },
            {
              code: "MAT230",
              name: "Linear and Vector Algebra for Engineers",
            },
            {
              code: "MAT260",
              name: "Differential Equations and Orthogonal Functions",
            },
          ],
        },
        {
          name: "Department of Law",
          skills: [
            "Legal system overview",
            "Court structure",
            "Legal processes",
            "Sources of law",
            "Constitutional principles",
            "Fundamental rights",
            "Government structure",
            "Judicial review",
            "Contract formation",
            "Contract terms",
            "Breach of contract",
            "Remedies for breach",
            "Marriage laws",
            "Divorce procedures",
            "Property rights",
            "Inheritance laws",
            "Criminal liability",
            "Types of crimes",
            "Defenses in criminal law",
            "Punishment and sentencing",
            "Employment contracts",
            "Workplace safety",
            "Labor disputes",
            "Collective bargaining",
            "Banking regulations",
            "Foreign exchange controls",
            "Financial institutions law",
            "Monetary policy",
            "Crime causation",
            "Criminal behavior",
            "Correctional systems",
            "Rehabilitation methods",
            "International crimes",
            "War crimes",
            "Genocide",
            "International tribunals",
            "Medical evidence",
            "Forensic science",
            "Expert testimony",
            "Medical malpractice",
            "Legal document drafting",
            "Contract preparation",
            "Conveyancing",
            "Legal writing",
            "Tax assessment",
            "Tax evasion",
            "Revenue collection",
            "Fiscal policy",
            "Legal clinic practice",
            "Client counseling",
            "Community service",
            "Pro bono work",
            "International treaties",
            "State sovereignty",
            "Diplomatic law",
            "International organizations",
            "Environmental protection",
            "Pollution control",
            "Natural resources",
            "Sustainable development",
            "Land ownership",
            "Land registration",
            "Tenancy laws",
            "Land disputes",
            "Cybercrime",
            "Data protection",
            "Media regulation",
            "Telecommunications law",
          ],
          courses: [
            {
              code: "LAW 101",
              name: "Introduction to Legal System & Legal Processes (3 cr)",
            },
            {
              code: "LAW 201",
              name: "Constitutional Law of Bangladesh (4 cr)",
            },
            {
              code: "LAW 107",
              name: "Law of Contract & Restitution (4 cr)",
            },
            {
              code: "LAW 211",
              name: "Family & Property Law (4 cr)",
            },
            {
              code: "LAW 213",
              name: "Law of Crimes (4 cr)",
            },
            {
              code: "LAW 405",
              name: "Labour & Employment Law (3 cr)",
            },
            {
              code: "LAW 417",
              name: "Banking & Foreign Exchange Law (3 cr)",
            },
            {
              code: "LAW 418",
              name: "Criminology & Penology (3 cr)",
            },
            {
              code: "LAW 419",
              name: "International Criminal Law (3 cr)",
            },
            {
              code: "LAW 420",
              name: "Medical Jurisprudence & Forensic Law (3 cr)",
            },
            {
              code: "LAW 418 (Alternate code)",
              name: "Legal Drafting (Civil & Criminal) & Conveyance (4 cr)",
            },
            {
              code: "LAW 419 (Alternate)",
              name: "Fiscal & Taxation Law (3 cr)",
            },
            {
              code: "LAW 420 (Alternate)",
              name: "Clinical Legal Education & Community Legal Service (4 cr)",
            },
            {
              code: "LAW 421",
              name: "Public International Law (3 cr)",
            },
            {
              code: "LAW 422",
              name: "Environmental Law & Policy of Bangladesh (3 cr)",
            },
            {
              code: "LAW 423",
              name: "Land Laws of Bangladesh (3 cr)",
            },
            {
              code: "LAW 424",
              name: "Cyber, Media & Telecommunications Law (3 cr)",
            },
          ],
        },
        {
          name: "Department of History & Philosophy",
          skills: [
            "Historical analysis",
            "Cultural studies",
            "Historical research",
            "Critical thinking",
            "Philosophical reasoning",
            "Critical analysis",
            "Logical thinking",
            "Ethical reasoning",
            "Moral philosophy",
            "Ethical theories",
            "Applied ethics",
            "Moral reasoning",
            "Scientific method",
            "Theory confirmation",
            "Scientific realism",
            "Philosophy of experimentation",
            "Corporate responsibility",
            "Ethical decision making",
            "Professional ethics",
            "Stakeholder theory",
            "Psychological theories",
            "Research methods",
            "Behavioral analysis",
            "Critical thinking",
            "Experimental design",
            "Data collection",
            "Statistical analysis",
            "Lab report writing",
            "Psychological concepts",
            "Human behavior",
            "Mental processes",
            "Psychological development",
            "Religious studies",
            "Comparative religion",
            "Cultural understanding",
            "Interfaith dialogue",
          ],
          courses: [
            {
              code: "HIS 101",
              name: "Bangladesh History & Culture",
            },
            {
              code: "PHI 101",
              name: "Introduction to Philosophy",
            },
            {
              code: "PHI 104",
              name: "Introduction to Ethics",
            },
            {
              code: "PHI 270",
              name: "Philosophy of Science",
            },
            {
              code: "PHI 401",
              name: "Business Ethics",
            },
            {
              code: "PSY 101",
              name: "Introduction to Psychology",
            },
            {
              code: "PSY 101L",
              name: "Introduction to Psychology Lab",
            },
            {
              code: "PSY 105",
              name: "Elements of Psychology",
            },
            {
              code: "PSY 205",
              name: "Introduction to World Religions",
            },
          ],
        },
      ],
    },
  ],
};
